import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Cairo, Roboto } from "next/font/google";
import ReduxProvider from "@/provider/reduxProvider";
import { Directions, Languages } from "@/constants/enums";
import { Locale } from "@/i18n.config";
import { ToastContainer } from "react-toastify";
import NextAuthSessionProvider from "@/provider/nextAuthProvider";

export async function generateStaticParams() {
  return [{ locale: Languages.ARABIC }, { locale: Languages.ENGLISH }];
}

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const locale = (await params).locale;
  return (
    <html
      lang={locale}
      dir={locale === Languages.ARABIC ? Directions.RTL : Directions.LTR}
    >
      <body
        className={`flex flex-col min-h-screen ${
          locale === Languages.ARABIC ? cairo.className : roboto.className
        }`}
      >
        <NextAuthSessionProvider>
          <ReduxProvider>
            <Header />
            {children}

            <Footer />
            <ToastContainer
              position="top-center"
              autoClose={4000}
              hideProgressBar={true}
              newestOnTop={false}
              // closeButton={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
          </ReduxProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
